name: Exercise / Practice
description: Track a small coding task or practice drill
labels: [type:exercise, status:todo]
body:
  - type: input
    id: title
    attributes:
      label: Exercise Title
      placeholder: e.g. Flexbox Practice Layout
  - type: textarea
    id: instructions
    attributes:
      label: Instructions / Challenge Description
  - type: textarea
    id: goals
    attributes:
      label: What You’re Practising
      placeholder: e.g. Flexbox alignment and spacing
