# .github/workflows/auto-label.yml
name: Auto Label Issues

on:
  issues:
    types: [opened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
