# .github/workflows/prettier.yml
name: Prettify Code

on:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.json'
      - '**.html'
      - '**.css'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Prettier
        run: |
          npm install
          npx prettier --write .
