# .github/workflows/weekly-digest.yml
name: Weekly Progress Digest

on:
  schedule:
    - cron: '0 10 * * MON'

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - name: List in-progress issues
        run: gh issue list --label "status:in-progress" --limit 100
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
